### ISSUE TITLE
Error: Unknown or unexpected option: --esm

### ISSUE THREAD

**Issue by damianesteban** [awslabs/green-boost#43]
When I try to run `gboost deploy-dev` I get the following error:

```
/Users/damianesteban/.config/yarn/global/node_modules/arg/index.js:90
						throw err;
						^

Error: Unknown or unexpected option: --esm
    at arg (/Users/damianesteban/.config/yarn/global/node_modules/arg/index.js:88:19)
    at main (/Users/damianesteban/.config/yarn/global/node_modules/ts-node/dist/bin.js:18:67)
    at Object.<anonymous> (/Users/damianesteban/.config/yarn/global/node_modules/ts-node/dist/bin.js:351:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ARG_UNKNOWN_OPTION'
}

Subprocess exited with error 1
Error: Command failed: cdk --app "ts-node --esm src/app.ts" deploy damianesteban-back-end --require-approval never --outputs-file backEndStackOutputs.json
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:902:15)
    at deployDev (file:///Users/damianesteban/src/green-boost/my-gb-app/node_modules/gboost/lib/deploy-dev.js:18:9)
    at file:///Users/damianesteban/src/green-boost/my-gb-app/node_modules/gboost/lib/index.js:13:13
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 34273,
  stdout: null,
  stderr: null
}
```

In this case I'm using yarn, but I tried it with pnpm and I get the same error.

**Comment by damianesteban** [comment]
I fixed this by installing the most recent version of ts-node:

`pnpm add -g ts-node@latest`
